"""added auth

Revision ID: fc82411fd269
Revises: 70ea6884ba09
Create Date: 2025-02-18 23:11:52.626071

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc82411fd269"
down_revision: Union[str, None] = "70ea6884ba09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("ua", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("is_unlimited", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("tokens_user_id_fkey"), onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("tokens_pkey")),
        sa.UniqueConstraint("token", name=op.f("tokens_token_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###
